# fly.toml app configuration file generated for chatify on 2024-12-08T18:46:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatify'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2gb'
